name: recipe_gpt_flutter
description: "AI-powered recipe generation app built with Flutter and clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Networking & HTTP
  dio: ^5.4.3+1
  http: ^1.2.1

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Navigation
  go_router: ^14.2.7

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.3

  # Camera & Images
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3

  # UI & Theming
  material_color_utilities: ^0.11.1
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1

  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Markdown Display
  flutter_markdown: ^0.7.3+1
  markdown: ^7.2.2

  # Utilities
  equatable: ^2.0.5
  uuid: ^4.4.2
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  freezed: ^2.5.2

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_gen:
  output: lib/gen/
  line_length: 80 